# Generated by Django 5.0.2 on 2024-03-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
