# Generated by Django 5.0.2 on 2024-02-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_invoice_alter_document_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_number',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='invoice/'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('in_progress', 'In Progress'), ('cancel', 'Cancel')], max_length=20, null=True),
        ),
    ]
