# Generated by Django 5.0.2 on 2024-02-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_invoice_active_pay_invoice_pay_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
